apiVersion: v1
kind: Service
metadata:
  name: duration-transform-app
spec:
  selector:
    app: duration-transform-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: duration-transform-app
  name: duration-transform-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duration-transform-app
  template:
    metadata:
      labels:
        app: duration-transform-app
    spec:
      containers:
      - image: openjdk:8
        name: app
        ports:
        - containerPort: 8080
        command: ["bash", "-ec", "cd /opt
          && curl -O http://repo/transform.zip && unzip transform.zip
          && ./transform/bin/transform durationTf kafka-0.kafka:9092 duration-agg earliest logevent-1 duration-1"]