#=========================== Filebeat inputs =============================

filebeat.inputs:
  #logs from build jobs
  - type: log
    enabled: true
    paths:
      - /mnt/jenkins_home/jobs/*/builds/*/log
    fields:
      topic: "log-builds"
  # logs from slaves
  - type: log
    enabled: true
    paths:
      - /var/jenkins_home/logs/slaves/*/slave.log
    fields:
      topic: "log-slaves"


fields:
  protocol: "${PROTOCOL}"
  master: "${MASTER}"
  domain: "${DOMAIN}"
  domainSuffix: "${DOMAINSUFFIX}"

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

#================================ Outputs =====================================

output.kafka:
  hosts: ["kafka-0.kafka:9092"]
  topic: 'filebeat-%{[fields][topic]}-1'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

#================================ Processors =====================================

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
