#=========================== Filebeat inputs =============================

filebeat.inputs:
  #logs from build jobs
  - type: log
    enabled: true
    paths:
      - /mnt/jenkins_home/jobs/*/builds/*/log
  # logs from slaves
  - type: log
    enabled: true
    paths:
      - /var/jenkins_home/logs/slaves/*/slave.log

#TODO Jenkins master log

fields:
  protocol: "${PROTOCOL}"
  master: "${MASTER}"
  domain: "${DOMAIN}"

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

#================================ Outputs =====================================

output.kafka:
  hosts: ["kafka-0.kafka:9092"]
  topic: 'filebeat-1'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

#================================ Processors =====================================

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~