apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secret
  name: secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
        - image: alpine:3.8
          name: secret
          command: ["/bin/sh", "-ec", "while true; do echo sleeping 1s...; sleep 1; done"]
          volumeMounts:
          - name: foo
            mountPath: "/tmp/sec"
            readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: test.zip