
master:
  adminUser: "admin"
  adminPassword: "admin"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "3096Mi"
  targetPort: 8080
  serviceType: LoadBalancer
  slaveListenerServiceType: "ClusterIP"
  # List of plugins to be install during Jenkins master start
  installPlugins:
    - kubernetes:1.25.3
    - workflow-job:2.38
    - workflow-aggregator:2.6
    - credentials-binding:1.21
    - git:4.2.2
    - configuration-as-code:1.39
    - configuration-as-code-support:1.18
    - job-dsl:1.77
    - parameterized-trigger:2.36
  # List of groovy init scripts to be executed during Jenkins master start
  initScripts:
    - |
      import jenkins.model.Jenkins;
      Jenkins.instance.getItemByFullName("spring-framework").scheduleBuild2(0);
      try { Thread.sleep(1000); } catch (Exception e) { }
      Jenkins.instance.getItemByFullName("spring-framework").scheduleBuild2(0);
      try { Thread.sleep(1000); } catch (Exception e) { }
      Jenkins.instance.getItemByFullName("spring-framework").scheduleBuild2(0);
  JCasC:
    enabled: true
    configScripts:
       jobs-config: |
         jobs:
           - url: https://raw.githubusercontent.com/logevents/demo-infra/master/jobDslSeed.groovy
       script-approval: |
         security:
           scriptApproval:
             approvedSignatures:
               - method java.time.chrono.ChronoLocalDate isBefore java.time.chrono.ChronoLocalDate
       shared-libraries: |
         unclassified:
           globalLibraries:
             libraries:
               - name: "shared-lib"
                 retriever:
                   modernSCM:
                     scm:
                       git:
                         remote: "https://github.com/logevents/demo-infra-sharedlibs.git"
  sidecars:
    # Allows you to inject additional/other sidecars
    other:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.6.2
        args: []
        env:
          - name: "MASTER"
            value: "{{ tpl .Release.Name . }}"
          - name: "PROTOCOL"
            value: "http"
          - name: "DOMAIN"
            value: "{{ tpl .Release.Name . }}"
          - name: "DOMAINSUFFIX"
            value: "logevents.nowhere"
        volumeMounts:
          - name: filebeat-config
            mountPath: "/usr/share/filebeat/filebeat.yml"
            subPath: "filebeat-cm.yml"
          - name: jenkins-home
            mountPath: "/mnt/jenkins_home"
            readOnly: true
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
agent:
  enabled: true
  resources:
    requests:
      cpu: "1000m"
      memory: "4000Mi"
    limits:
      cpu: "1000m"
      memory: "4000Mi"
  # Max number of spawned agent
  containerCap: 3
  idleMinutes: 15
  slaveConnectTimeout: 100
persistence:
  enabled: true
  volumes:
    - name: filebeat-config
      configMap:
        name: jenkins-filebeat