apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093