apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  clusterIP: None
  ports:
    - protocol: TCP
      name: 'cluster'
      port: 9092
      targetPort: 9092
    - protocol: TCP
      name: 'internal'
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      enableServiceLinks: false
      containers:
        - image: confluentinc/cp-kafka:5.2.4
          name: kafka
          ports:
            - containerPort: 9091
            - containerPort: 9092
          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zoo:2881"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CLUSTER:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka-0.kafka:9091,CLUSTER://kafka-0.kafka:9092"
            - name: KAFKA_BROKER_ID_GENERATION_ENABLE
              value: "false"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_HEAP_OPTS
              value: "-Xms1000M -Xmx1000M"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "1200Mi"
              cpu: "250m"
            limits:
              memory: "1400Mi"
              cpu: "500m"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi