apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      enableServiceLinks: false
      containers:
        - image: docker.elastic.co/kibana/kibana:7.5.2
          name: kibana
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elastic:9200"
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "1200Mi"
              cpu: "500m"