apiVersion: v1
kind: Service
metadata:
  name: repo
spec:
  selector:
    app: repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-nginx-conf
data:
  hello.html: |
    <!DOCTYPE html>
    <html lang="en">
    <body>
    hi there
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: repo
  name: repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo
  template:
    metadata:
      labels:
        app: repo
    spec:
      enableServiceLinks: false
      containers:
        - image: nginx:latest
          name: repo
          ports:
            - containerPort: 80
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/hello.html
              subPath: hello.html
      volumes:
        - name: config-volume
          configMap:
            name: repo-nginx-conf
            items:
             - key: hello.html
               path: hello.html
